language: fortran
addons:
  apt:
    packages:
      - gfortran
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j clean all $TEST
matrix:
  include:
    - os: osx
      env:
        - TEST="unittests"
      osx_image: xcode12.5
    - os: linux
      env:
        - TEST="unittests"
      dist: focal
      sudo: required
