name: amber
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - numpy
  - scipy
  - jupyterlab
  - tensorflow >= 2.10
  - tensorflow-probability >= 0.18
  # testing
  - pytest
  - pytest-cov
  # coding
  - black
