name: tf2-nomkl
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - nomkl
  - numpy
  - scipy
  - netcdf4
  - h5py
  - matplotlib
  - pandas
  - geopandas
  - jupyterlab
  - tensorflow >= 2.11
  - tensorflow-probability >= 0.19
  - scikit-learn
  - seaborn
  - cartopy
  - xarray
  # testing
  - pytest
