name: amber
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - numba
  - numpy = 1.26.4
  - tensorflow = 2.14.0
  - tensorflow-probability
  # extra
  - jupyterlab
  # test
  - pytest
  - pytest-cov
  # lint
  - black
  - flake8
