name: amber
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - numpy
  - scipy
  - tensorflow >= 2.12.0
  # extra
  - tensorflow-probability
  - jupyterlab
  # test
  - pytest
  - pytest-cov
  # lint
  - black
  - flake8
