name: amber
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - numpy
  - scipy
  - jupyterlab
  - tensorflow >= 2.12.0
  - tensorflow-probability
  # testing
  - pytest
  - pytest-cov
  # coding
  - black
  - flake8
