name: amber
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - nomkl
  - numba
  - numpy = 1.26.4
  - scipy
  - tensorflow = 2.14.0
  # extra
  - jupyterlab
  - tensorflow-probability
  # test
  - pytest
  - pytest-cov
  # lint
  - black
  - black-jupyter
  - flake8
