name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conda
        working-directory: ${{github.workspace}}/build
        run: |
          conda env create --file=./environment-nomkl.yml
          conda activate tf2-nomkl

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          pytest --disable-warnings
         
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conda
        working-directory: ${{github.workspace}}/build
        run: |
          conda env create --file=./environment.yml
          conda activate tf2

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          pytest --disable-warnings
